# Generated by Django 4.0.8 on 2022-11-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=99.99, max_digits=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
