# Generated by Django 4.0.8 on 2022-11-19 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_product_image_cart_user_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
